FROM mysql:5.7

WORKDIR /var/lib/mysql/

#senha do MYSQL
ENV MYSQL_ROOT_PASSWORD=Senha123

#Endereço do banco de Dados MYSQL
ENV MYSQL_DATABASE=meubanco

ADD sdl.sql /docker-entrypoint-initdb.d

EXPOSE 3306